<?php include 'navigation.inc'; ?>
<div class="row">
	<div class="col-xs-0 col-sm-0 col-md-2"></div>
	<div class="col-md-8" >
	<table class="table table-striped">
		<caption class="text-center"><h3>Avaliable Quiz List</h3></caption>
		<thead>
			<tr>
				<th>No.</th>
				<th>Quiz List</th>
				<th>Discription</th>
				<th>Progress</th>
				<th>&nbsp;</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1.</td>
				<td>Quiz 1</td>
				<td><span class="btn btn-success">Easy</span></td>
				<td>
				<div class="progress progress-striped">
					<div class="progress-bar progress-bar-info" style="width:80%" ></div>
				</div>
				</td>
				<td class="text-right"><button class="btn btn-info">Take quiz</button></td>
			</tr>
		</tbody>
	</table>
	</div>
</div>