<meta name="viewport" content="width=device-width, initial-scale=1">

	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">

<?php
/*
	<link rel="stylesheet" href="library/bootstrap/css/bootstrap.css">
	<script src="library/jquery/jquery.js"></script>
	<script src="library/bootstrap/js/bootstrap.js"></script>
	<link rel="stylesheet" href="library/font-awesome/css/font-awesome.min.css">
*/
?>	
	
<link rel="stylesheet" type="text/css" href="style.css"/>